### ISSUE TITLE
Custom CSS for CHAOSScon 19 EU website

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#101]
Hi @klumb, 

Can you please add the following custom CSS to the CHAOSScon19EU page to make the speaker profiles look like this?

```CSS
img {
    float: left;
    margin-right: 10px;
}
h3 {
    clear: left;
}
```

![image](https://user-images.githubusercontent.com/8862021/50174556-20df6b00-02c0-11e9-8770-10f7b3cc9625.png)
